# Generated by Django 5.2.8 on 2025-11-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter',
            new_name='instagram',
        ),
    ]
