# Generated by Django 5.2.8 on 2025-11-16 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_rename_twitter_teammember_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('nombre_jours', models.IntegerField(default=1)),
                ('lieu', models.CharField(max_length=200)),
                ('points_par_jour', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AlterModelOptions(
            name='membres',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='membres',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membres',
            name='uuid_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('jours_assistes', models.IntegerField()),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='membres.membres')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='membres.evenement')),
            ],
            options={
                'ordering': ['-date_obtention'],
                'unique_together': {('membre', 'evenement')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='present', max_length=20)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='membres.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='membres.membres')),
            ],
            options={
                'ordering': ['-date_scan'],
                'unique_together': {('membre', 'evenement', 'jour')},
            },
        ),
    ]
