# Generated by Django 5.2.8 on 2025-11-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_evenement_alter_membres_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='membres.membres'),
        ),
    ]
