# Generated by Django 5.2.8 on 2025-12-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_evenement_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='certificats_pdfs/', verbose_name='Fichier PDF (Personnalisé)'),
        ),
    ]
