# Generated by Django 5.2.8 on 2025-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0006_certificate_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_certificat',
            field=models.ImageField(blank=True, null=True, upload_to='certificats_templates/', verbose_name='Modèle de certificat (Image Vide)'),
        ),
    ]
