# Generated by Django 5.2.8 on 2025-12-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0007_certificate_image_certificat'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='cert_nom_x',
            field=models.IntegerField(default=420, help_text='Centre de la page A4 = 420 environ', verbose_name='Position X du Nom (Gauche <-> Droite)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='cert_nom_y',
            field=models.IntegerField(default=300, help_text='0 = Tout en bas. 595 = Tout en haut.', verbose_name='Position Y du Nom (Bas <-> Haut)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='cert_text_color',
            field=models.CharField(default='#000000', help_text='Ex: #000000 pour noir, #FFFFFF pour blanc, #FFD700 pour or', max_length=7, verbose_name='Couleur du texte (Hex)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='image_certificat',
            field=models.ImageField(blank=True, null=True, upload_to='certificats_templates/', verbose_name='Image de fond (Template)'),
        ),
    ]
