# Generated by Django 5.2.8 on 2025-12-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0008_evenement_cert_nom_x_evenement_cert_nom_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image_certificat',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_nom_x',
            field=models.IntegerField(default=420, verbose_name='Position X (Gauche/Droite)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_nom_y',
            field=models.IntegerField(default=300, verbose_name='Position Y (Bas/Haut)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Couleur Texte (Hex)'),
        ),
    ]
