# Generated by Django 5.2.8 on 2025-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0009_remove_certificate_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='police_ttf',
            field=models.FileField(blank=True, help_text='Laissez vide pour utiliser Helvetica par défaut.', null=True, upload_to='fonts/', verbose_name='Fichier Police (.ttf)'),
        ),
    ]
