# Generated by Django 5.2.8 on 2026-01-15 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0010_certificate_police_ttf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_obtention'], 'verbose_name': 'Certificat Délivré', 'verbose_name_plural': 'Certificats Délivrés'},
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='membres',
            options={'ordering': ['nom'], 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date_scan'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cert_nom_x',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cert_nom_y',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cert_text_color',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='jours_assistes',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='police_ttf',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='cert_nom_x',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='cert_nom_y',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='cert_text_color',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='image_certificat',
        ),
        migrations.AddField(
            model_name='certificate',
            name='code_verification',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_delivres', to='membres.evenement'),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fond', models.ImageField(upload_to='certificats_templates/', verbose_name='Image de fond (A4 Paysage)')),
                ('nom_x', models.IntegerField(default=420, help_text='Centre ~420', verbose_name='Position X du Nom')),
                ('nom_y', models.IntegerField(default=300, help_text='Bas=0, Haut=595', verbose_name='Position Y du Nom')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Couleur Texte (Hex)')),
                ('police_ttf', models.FileField(blank=True, help_text='Laissez vide pour Helvetica standard.', null=True, upload_to='fonts/', verbose_name='Police personnalisée (.ttf)')),
                ('taille_police', models.IntegerField(default=45, verbose_name='Taille de la police')),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_certificat', to='membres.evenement', verbose_name='Événement associé')),
            ],
            options={
                'verbose_name': 'Configuration du Certificat',
                'verbose_name_plural': 'Configurations des Certificats',
            },
        ),
    ]
