# Generated by Django 5.2.8 on 2026-01-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0011_alter_annonce_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='sign_x',
            field=models.IntegerField(default=600, verbose_name='Pos X Signature'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='sign_y',
            field=models.IntegerField(default=150, verbose_name='Pos Y Signature'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature (PNG Transparent)'),
        ),
    ]
